const fs = require('fs')
const path = require('path')
const { rgbToLab } = require('../services/image/colorSpace')

const root = path.resolve(__dirname, '..')
const sourcePath = path.join(root, 'data', 'mard221.source.json')
const outputPath = path.join(root, 'data', 'mard221.js')
const source = JSON.parse(fs.readFileSync(sourcePath, 'utf8'))

if (source.count !== 221 || source.colors.length !== 221) {
  throw new Error(`Expected 221 MARD colors, received ${source.colors.length}`)
}

const colors = source.colors.map(color => ({
  code: color.code,
  hex: color.hex.toUpperCase(),
  rgb: color.rgb,
  lab: rgbToLab(color.rgb).map(value => Number(value.toFixed(5)))
}))

const banner = `// Generated by scripts/build_mard_palette.js\n` +
  `// Source: https://github.com/HansBug/pindou-color-data/tree/main/mard-221-alfonse-doudou\n` +
  `// License: MIT; see data/licenses/pindou-color-data-MIT.txt\n`
const serialized = JSON.stringify(colors, null, 2)
const moduleText = `${banner}const MARD221 = ${serialized}\n\n` +
  `if (typeof module !== 'undefined' && module.exports) module.exports = MARD221\n` +
  `if (typeof window !== 'undefined') window.MARD221 = MARD221\n`

fs.writeFileSync(outputPath, moduleText)
console.log(`Wrote ${colors.length} colors to ${outputPath}`)
